Repository w3c/web-roadmaps, pull requests merged in 2018-06, with the labels that each got.

#264 [mobile] Update the description of payment-method-basic-card
  js/translations.zh.json
  mobile/payment.html
  mobile/payment.zh.html
Labels: mobile-roadmap

#263 [mobile] Mention Indexed Database API 3.0
  mobile/storage.html
  mobile/storage.zh.html
Labels: mobile-roadmap

#265 [Framework] Custom maturity icons for evergreen/informative specs
  README.md
  js/generate-utils.js
  js/translations.json
  tools/extract-spec-data.js
  tools/spec.jsons
  tools/tr.jsons
Labels: enhancement, framework

#266 [Framework] New "See also" column in summary tables
  README.md
  assets/css/theme.css
  js/generate-utils.js
  js/translations.json
  js/translations.zh.json
  tools/extract-spec-data.js
  tools/spec.jsons
  tools/tr.jsons
Labels: enhancement, framework

#267 [Framework] New "milestones" column in summary tables
  README.md
  assets/css/theme.css
  js/generate-utils.js
  js/translations.json
  tools/extract-spec-data.js
  tools/spec.jsons
  tools/tr.jsons
Labels: enhancement, framework

#268 [Framework] Make nav menu not dependent on JS
  assets/css/roadmap.css
  js/generate-utils.js
  js/sidenav.js
  js/template-page.html
  js/template-page.zh.html
Labels: enhancement, framework

#269 [Framework] Allow status property in spec description
  README.md
  tools/spec.jsons
Labels: enhancement, framework

#270 Framework specfeature
  README.md
  assets/css/theme.css
  assets/impl/partial.svg
  data/picture-in-picture.json
  data/storage.json
  js/generate-utils.js
  js/service-worker.js
  js/template-about.html
  js/template-about.zh.html
  js/template-page.html
  js/template-page.zh.html
  package.json
  tools/extract-impl-data.js
  tools/extract-spec-data.js
  tools/impl.jsons
  tools/spec.jsons
  tools/tr.jsons
Labels: enhancement, framework

#272 [Framework] New tool to create missing data files for W3C specs
  README.md
  js/generate-utils.js
  package.json
  tools/create-missing-data.js
  tools/extract-spec-data.js
Labels: data, enhancement, framework

#273 [Framework] Add mechanism to link to the ED
  README.md
  js/generate-utils.js
  js/generate.js
Labels: enhancement, framework
